mongodb:
  image: mongo
  port: 27017

backend:
  image: shakti827/mern-backend
  containerPort: 3000
  servicePort: 3000

frontend:
  image: shakti827/mern-frontend
  containerPort: 3000
  servicePort: 3000
  nodePort: 30080

autoscaling:
  enabled: false

serviceAccount:
  create: false
  name: ""

ingress:
  enabled: false

service:
  type: ClusterIP
  port: 3000

